create table if not exists public.room_checklist (
  id bigint generated by default as identity primary key,
  room text not null,
  code text not null,
  room_type text not null,
  checklist_date date not null,
  area text not null,
  utility text not null,
  condition text not null default 'NORMAL' check (condition in ('NORMAL','DEFECT')),
  notes text not null default '',
  update_smarthome boolean not null default false,
  sort_no integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists room_checklist_unique_row
  on public.room_checklist (room, checklist_date, area, utility);

create index if not exists room_checklist_room_date_idx
  on public.room_checklist (room, checklist_date desc, sort_no asc);

create or replace function public.set_room_checklist_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_room_checklist_updated_at on public.room_checklist;
create trigger trg_room_checklist_updated_at
before update on public.room_checklist
for each row execute function public.set_room_checklist_updated_at();
